name: fed_enviro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas=2.2
  - notebook=7.0
  - ipykernel
  - pip:
    - requests==2.31
    - plotly==5.22
    - pytest==7.4
    - black==24.3
    - poetry==1.6.1
```# filepath: /Users/sajidahmed/Desktop/ps1_first_repo/fed/environment.yml
name: fed_enviro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas=2.2
  - notebook=7.0
  - ipykernel
  - pip:
    - requests==2.31
    - plotly==5.22
    - pytest==7.4
    - black==24.3
    - poetry==1.6.1