# Project configuration for the fed package; uses "fed_enviro" as the intended environment name.

[tool.poetry]
name = "fed"
version = "0.1.0"
description = "Utilities for fetching, cleaning and plotting GDP data."
authors = ["sajidahmed <sajid@example.com>"]
packages = [{ include = "fed" }]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2"
requests = "^2.31"
plotly = "^5.22"
notebook = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4"
black = "^24.3"

[tool.poetry.scripts]
# optional entrypoint examples
run-gdp = "fed.data:fetch_data"

[tool.fed_enviro]
env_name = "fed_enviro"
manager = "poetry"
note = "This custom section indicates the virtual environment name to use for this project."

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
```# filepath: /Users/sajidahmed/Desktop/ps1_first_repo/fed/py_project.toml
# Project configuration for the fed package; uses "fed_enviro" as the intended environment name.

[tool.poetry]
name = "fed"
version = "0.1.0"
description = "Utilities for fetching, cleaning and plotting GDP data."
authors = ["sajidahmed <sajid@example.com>"]
packages = [{ include = "fed" }]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2"
requests = "^2.31"
plotly = "^5.22"
notebook = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4"
black = "^24.3"

[tool.poetry.scripts]
# optional entrypoint examples
run-gdp = "fed.data:fetch_data"

[tool.fed_enviro]
env_name = "fed_enviro"
manager = "poetry"
note = "This custom section indicates the virtual environment name to use for this project."

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"